eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

## Tomcat Server Port
server:
  port: 8099

core:
  authorized:
    client: "*"

spring:
  ## DataSource settings:
  datasource:
    url: jdbc:mysql://localhost:3306/bangel_messages?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driverClassName:  com.mysql.cj.jdbc.Driver
    ## DevTools Proprieties
    #spring.devtools.restart.enabled=false
    #spring.devtools.livereload.enabled=false
    testWhileIdle:  true
    timeBetweenEvictionRunsMillis:  60000
    validationQuery:  SELECT 1

  ## Specify the DBMS
  jpa:
    database:  MYSQL
    ## Show or not log for each sql query
    show-sql:  true
    ## Hibernate ddl auto (create, create-drop, update) create DB if doesn't exist
    hibernate.ddl-auto: update
    ## Naming strategy
    properties.hibernate.dialect:  org.hibernate.dialect.MySQL5Dialect

