spring:
  mail:
    host: smtp.gmail.com
    username: beangel.norsys.afrique@gmail.com
    password: NABAngel*
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          socketFactory:
            port: 465
  cloud:
    config:
      discovery:
        enabled: true

server:
  port: 8094
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    
# mail properties
from: beangel.norsys.afrique@gmail.com

CORDIALEMENT: "\n\n Cordialement\n---------------------------------------------------------------------\n"
LIEN_APPLICATION: "\nAccés à l'application   http://localhost:4444"

# ressource mail properties
RECUPERATION_MOTDEPASSE_SUBJECT: "Récupération de mot de passe"
RECUPERATION_MOTDEPASSE_CONTENT: "Bonjour ,\n\nSuite à votre demande, une regénération de votre mot de passe pour l'accès au système d’information Norsys Afrique s'est effectuée avec succés. \nVotre nouveau mot de passe \t : " 

CREATION_COMPTE_SUBJECT: "Création de compte Bangel"
CREATION_COMPTE_CONTENT: "Bonjour,\n\nUn compte vous a été créé sur le système d’information de Bangel. \nVeuillez confirmer votre inscription : "




