spring:
  application:
    name: mail-service
  mail:
    host: smtp.gmail.com
    username: beangel.norsys.afrique@gmail.com
    password: NABAngel*
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          socketFactory:
            port: 465
  cloud:
    config:
      discovery:
        enabled: true

server:
  port: 8094
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


