spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bangel_projects?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver
    tomcat:
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate :
        dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
queue:
  name: messagequeue

fanout:
  exchange: messagequeue-exchange

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
server:
  port: 8092


