spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: -1
      max-request-size: -1

server:
  port: 8098

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
file:
  upload-dir: C:\\server\\uploads
