spring:
  servlet:
    multipart:
      max-file-size: 20MB
	    max-request-size: 20MB

server:
  port: 8098

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
file:
  upload-dir: C:\\server\\uploads
